### ISSUE TITLE
Compatibility with `flatc`

### ISSUE THREAD

**Issue by dzqv** [liuliu/dflat#3]
This project looks extremely cool; a better Core Data is much appreciated.  Our servers are written in Go and use `flatc` generated codecs, so we were wondering if this project maintains any tests ensuring compatibility between `flatc` and `dflatc` generated code or if that's a goal / in-scope.

**Comment by liuliu** [comment]
Thanks. There is nothing special about the FlatBuffers encoding in `dflatc`. It simply calls the Swift FlatBuffers compiler maintained within main tree at https://github.com/google/flatbuffers/tree/master/swift The compatibility guarantee is based on using the same code as the main tree, which should be inferred there.
